### ISSUE TITLE
Wave simulation

### ISSUE THREAD

**Issue by cryer** [k-ye/PbfVs#4]
我想问一下，我大概跑了一下这个项目，好像是炒兔模拟器，并不是md文件动图的流体仿真

**Comment by k-ye** [comment]
抱歉，这个project场景设置都是hard-coded。如果你回滚到
48a4e417ab40515358301d3f87547b5b9af99301这个commit（2018年以前的commit），那时候的场景是流体仿真。新的炒兔模拟器主要是为了知乎回答才开发的 :)

**Comment by cryer** [comment]
哈哈，好的，谢谢回答

**Comment by cryer** [comment]
你好，抱歉再稍微打扰一下，我想问一下您，那个md文档里960M跑流体的那个GIF是原速吗？还是加速过了。。我笔记本1050Ti跑这种就慢的不行，完全一帧一帧慢慢的跑

**Comment by k-ye** [comment]
是的嗯...我没有做过任何剪辑，但是有可能commit了一些实验性的config。不知道你调一下https://github.com/k-ye/PbfVs/blob/master/PbfVs/Config/config.txt这个文件（比如减少num_particles_width=36, num_particles_height=36, num_particle_layers=15）会不会好一些？
